version: "3.8"
services:
  frontend:
    build:
      context: ./fe
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./be/src
    ports:
      - "5000:5000"
